[tools]
node = "24.11"
python = "3.10"
go = "1.24"
ruby = "3.3"
rust = "1.91"
deno = "2.5"
yarn = "1.22"
bun = "1.2"
pnpm = "10"
uv = "latest"
"npm:@vivliostyle/cli" = "latest"
"go:github.com/boyter/scc" = "latest"
"npm:tsx" = "latest"
"npm:@anthropic-ai/claude-code" = "latest"
"npm:wrangler" = "latest"
"npm:@google/gemini-cli" = "latest"
"npm:@openai/codex" = "latest"

[settings]
experimental = true
idiomatic_version_file_enable_tools = ["node"]

[settings.npm]
bun = true
