---
homebrew_taps:
  - oven-sh/bun

homebrew_packages:
  # - { name: ansible}
  - { name: asciinema }
  - { name: autoconf }
  - { name: autojump }
  - { name: automake }
  - { name: awscli }
  - { name: boost }
  - { name: brotli }
  - { name: bun }
  #- { name: cabal-install }
  - { name: cairo }
  - { name: carthage }
  - { name: cmake }
  - { name: cowsay }
  - { name: coreutils }
  - { name: curl }
  - { name: editorconfig }
  - { name: ffmpeg }
  # - { name: flow }
  - { name: gcc }
  - { name: gh }
  #- { name: ghc }
  - { name: ghostscript }
  - { name: gibo }
  - { name: git }
  - { name: git-lfs }
  - { name: gpg }
  - { name: graphviz }
  - { name: htop }
  - { name: hub }
  - { name: imagemagick }
  - { name: jpeg }
  - { name: jq }
  #- { name: int128/kubelogin/kubelogin }
  - { name: kubernetes-cli }
  - { name: lame }
  - { name: libpng }
  - { name: libtiff }
  - { name: libtool }
  - { name: llvm }
  #- { name: mecab }
  #- { name: mecab-ipadic }
  - { name: memcached }
  - { name: mercurial }
  - { name: mkcert }
  - { name: mysql }
  - { name: neovim }
  - { name: nginx }
  - { name: nkf }
  - { name: openssl }
  - { name: openssl, state: linked, install_options: force }
  - { name: peco }
  - { name: pkg-config }
  # - { name: rbenv }
  # - { name: ruby-build }
  - { name: readline }
  - { name: redis }
  #- { name: sbt }
  - { name: sqlite }
  - { name: tcl-tk }
  - { name: tig }
  - { name: tmux }
  - { name: tree }
  - { name: watch }
  # - { name: watchman }
  - { name: wget }
  - { name: xz }
  - { name: yq }
  - { name: zlib }
  - { name: zsh }

homebrew_cask_packages:
  #- { name: '0xed' }
  - { name: adobe-creative-cloud }
  # - { name: adoptopenjdk }
  #- { name: android-sdk }
  - { name: ankerwork }
  # - { name: atom }
  - { name: brave-browser }
  # - { name: charles }
  - { name: coteditor }
  - { name: db-browser-for-sqlite }
  - { name: deepl }
  - { name: discord }
  - { name: docker }
  - { name: dropbox }
  - { name: figma }
  - { name: firefox }
  - { name: firefox@nightly }
  # - { name: fontexplorer-x-pro }
  #- { name: github }
  - { name: glyphs }
  - { name: google-drive }
  #- { name: google-chrome }
  - { name: google-chrome@beta }
  - { name: google-chrome@canary }
  - { name: google-cloud-sdk }
  # - { name: google-japanese-ime }
  #- { name: grammarly }
  - { name: grandperspective }
  # - { name: gyazo }
  #- { name: hyper }
  # - { name: iterm2 }
  - { name: jetbrains-toolbox }
  - { name: karabiner-elements }
  - { name: kap }
  - { name: keycastr }
  - { name: medis }
  #- { name: nextcloud}
  - { name: proxyman }
  - { name: raycast }
  #- { name: rightfont }
  - { name: safari-technology-preview }
  - { name: sequel-ace }
  # - { name: sketch }
  #- { name: skype }
  - { name: slack }
  - { name: sloth }
  - { name: spotify }
  #- { name: vagrant }
  #- { name: virtualbox }
  - { name: visual-studio-code }
  - { name: vlc }
  #- { name: vmware-fusion }
  #- { name: wireshark }
  - { name: zeplin }
  - { name: zoom }
